### Listar tarefas
GET http://localhost:3000/tarefas


### Criar tarefa com projeto
POST http://localhost:3000/tarefas
Content-Type: application/json

{
  "descricao": "Criar integração entre projetos e tarefas",
  "projetoId": 1
}


### Listar novamente
GET http://localhost:3000/tarefas


### Buscar tarefa por ID
GET http://localhost:3000/tarefas/1


### Resumo
GET http://localhost:3000/tarefas/resumo